### ISSUE TITLE
Incorrect color format

### ISSUE THREAD

**Issue by QuasiStellar** [und3f/PixelartToVector#6]
<img width="708" alt="image" src="https://github.com/und3f/vectorize-pixelart/assets/30569097/ae88b8bd-8ba9-47a8-bd71-6f998f32b5d9">

Trying to use generated svgs in Intelij IDEA to generate assets, getting this error.

**Comment by und3f** [comment]
Hi, please test the fixed version.
upd: It is not yet published to npm or site, just to master branch

**Comment by und3f** [comment]
I've updated web version as well
